version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
- macOS
install: pwsh -c ./appveyor_install.ps1
build_script: pwsh -c ./appveyor_build.ps1
test_script:
- pwsh: >-
    if($IsWindows){$env:PATH += ";/tools/ldc/bin"}
    dub test --parallel