version: '{build}'
image:
- Ubuntu
- Visual Studio 2019
- macOS
install: pwsh -c appveyor/install.ps1
build_script: pwsh -c appveyor/build.ps1
test_script: pwsh -c appveyor/test.ps1
artifacts:
- path: "*fpm*"
- path: util/flink/*flink*
- path: util/rflink/*rflink*
- path: util/uflink/*uflink*
- path: util/smerge/*smerge*