version: '{build}'
image:
- macOS
- Ubuntu
- Visual Studio 2019
install:
- pwsh: >-
    if($IsMacOS){

    brew install dub ldc

    } if ($IsLinux){

    sudo snap install --classic --channel=edge ldc2

    sudo snap install --classic --channel=edge dub

    } if ($IsWindows){

    choco install ldc

    mv /tools/ldc* /tools/ldc

    }
build_script:
- pwsh: >-
    if($IsWindows){$env:PATH += ";/tools/ldc/bin"}

    dub run :rflink -b release -c lib --parallel -- -h

    dub run :uflink -b release -c lib --parallel -- -h

    dub run :smerge -b release -c lib --parallel -- -h

    dub run -b release -c lib --parallel -- -h

    dub run :flink -b release --parallel -- -h

    dub run :rflink -b release --parallel -- -h

    dub run :uflink -b release --parallel -- -h

    dub run :smerge -b release --parallel -- -h

    dub run -b release --parallel -- -h
test_script:
- pwsh: >-
    if($IsWindows){$env:PATH += ";/tools/ldc/bin"}

    dub test --parallel
artifacts:
- path: fpm
  name: fpm unix
- path: util/flink/flink
  name: flink unix
- path: util/rflink/rflink
  name: rflink unix
- path: util/uflink/uflink
  name: uflink unix
- path: util/smerge/smerge
  name: smerge unix
- path: "**/*.a"
  name: unix static library
- path: "**/*.lib"
  name: windows static library
- path: "**/*.exe"
  name: windows program
#- path: "**/*.h"
#  name: C header